# Generated by Django 3.1.1 on 2020-09-07 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groclist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groclist',
            name='buy_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groclist',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groclist',
            name='qty',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
