# Generated by Django 3.1.1 on 2020-09-08 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groclist', '0002_auto_20200907_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groclist',
            name='qty',
        ),
    ]
